build: 
	docker build -t local/wendihub .          # local name, add to cyberhubs/multiuser/jupyterhub_config.py 
#	docker build -t ${JUPYTER_SGLEUSR_IMG} .  # system name as defined in cyberhubs/scripts/jupyterhub-config-script.sh 
