jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Star_explore.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/NuGrid Set Explorer self-guided interface.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/README.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/write_initial_abu_test.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/abundance_profile_at_collapse.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/Teaching_explore_MESA_stellar_evolution.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/Explosion_explore.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/C-burn_massive_iniabu.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/decay_isotope_and_elements.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/Presolar_Grain_Workshop_2015.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/Tbot_envelope-HBB.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/Extract_trajectory.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/3d_plot_abu_chart.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/using_specific_nugridpy_release.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/data_mining_massive_stars.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/Infall_velocities.ipynb'
jupyter trust '/home/user/notebooks/Stellar evolution and nucleosynthesis data/Examples/C13-pocket-analysis.ipynb'
jupyter trust '/home/user/notebooks/One-zone Model for the Evolution of GAlaxies (OMEGA)/OMEGA self-guided interface.ipynb'
jupyter trust '/home/user/notebooks/One-zone Model for the Evolution of GAlaxies (OMEGA)/OMEGA demo and teaching notebooks/First_steps_OMEGA_2_open_box.ipynb'
jupyter trust '/home/user/notebooks/One-zone Model for the Evolution of GAlaxies (OMEGA)/OMEGA demo and teaching notebooks/First_steps_OMEGA_3_fitting_a_galaxy.ipynb'
jupyter trust '/home/user/notebooks/One-zone Model for the Evolution of GAlaxies (OMEGA)/OMEGA demo and teaching notebooks/First_steps_OMEGA_1_closed_box.ipynb'
jupyter trust '/home/user/notebooks/Stellar Yields for Galactic Modeling Applications (SYGMA)/SYGMA self-guided user interface.ipynb'
jupyter trust '/home/user/notebooks/Stellar Yields for Galactic Modeling Applications (SYGMA)/Analysis and plots from the SYGMA paper/Section4.2.ipynb'
jupyter trust '/home/user/notebooks/Stellar Yields for Galactic Modeling Applications (SYGMA)/Analysis and plots from the SYGMA paper/Section4.1.ipynb'
jupyter trust '/home/user/notebooks/Stellar Yields for Galactic Modeling Applications (SYGMA)/Analysis and plots from the SYGMA paper/Section3.ipynb'
jupyter trust '/home/user/notebooks/Stellar Yields for Galactic Modeling Applications (SYGMA)/Analysis and plots from the SYGMA paper/Section2.ipynb'
